test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: startuser
  password: password
  database: start

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: startuser
  password: password
  database: start

production:
  adapter: postgresql
  encoding: unicode
  host: <%= Rails.application.credentials[:production][:database][:host] %>
  port: <%= Rails.application.credentials[:production][:database][:port] %>
  username: <%= Rails.application.credentials[:production][:database][:username] %>
  password: <%= Rails.application.credentials[:production][:database][:password] %>
  database: <%= Rails.application.credentials[:production][:database][:database] %>